####################################################################################################

version: 1

####################################################################################################

formatters:

  simple:
    format: '%(asctime)s - %(name)s - %(module)s.%(funcName)s - %(levelname)s - %(message)s'

  ansi:
#   RESET_SEQ = "\033[0m"
#   COLOR_SEQ = "\033[1;%dm"
#   BOLD_SEQ = "\033[1m"
    format: '<ESC>[1;32m%(asctime)s<ESC>[0m - <ESC>[1;34m%(name)s - %(module)s.%(funcName)s<ESC>[0m - <ESC>[1;31m%(levelname)s<ESC>[0m - %(message)s'

####################################################################################################

handlers:

  console:
    class: logging.StreamHandler
    # level: DEBUG
    # level: INFO
    # level: WARNING
    formatter: ansi
    stream: ext://sys.stdout

####################################################################################################

root:
  # level: DEBUG
  # level: INFO
  level: WARNING
  # handlers: [console]

####################################################################################################

loggers:

##################################################
#
# Programs
#

  pyqgit:
    # level: DEBUG
    # level: INFO
    level: WARNING
    handlers: [console]
    propagate: no

  diff-viewer:
    # level: DEBUG
    # level: INFO
    level: WARNING
    handlers: [console]
    propagate: no

##################################################
#
# Modules
#

  CodeReview:
    # level: DEBUG
    # level: INFO
    # level: WARNING
    handlers: [console]
