#! /usr/bin/env python3

####################################################################################################
#
# CodeReview - A Code Review GUI
# Copyright (C) 2019 Fabrice Salvaire
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
####################################################################################################

####################################################################################################

from pathlib import Path
import argparse
import subprocess

####################################################################################################

parser = argparse.ArgumentParser(description='Generate PNG files from a SVG.')
parser.add_argument(
    'svg_path', metavar='file.svg',
    help='SVG PATH',
)
args = parser.parse_args()

svg_path = Path(args.svg_path).resolve()

####################################################################################################

sizes = (32, 64, 96, 128, 256, 512)

inkscape_options = [
    '--export-area-page',
    '--export-background=white',
    '--export-background-opacity=0',
]

####################################################################################################

def run_inkscape(svg_path, size):
    command = (
        'inkscape',
        *inkscape_options,
        '--export-png=logo-{}.png'.format(size),
        # --export-width=
        '--export-height={}'.format(size),
        str(svg_path),
    )
    print('>', ' '.join(command))
    subprocess.check_call(command)

####################################################################################################

for size in sizes:
    run_inkscape(svg_path, size)
