#! /bin/bash

# bdist
# python setup.py check --verbose --metadata --restructuredtext --strict && \
#   python setup.py register sdist upload

python setup.py bdist_wheel

twine register dist/*whl
gpg --detach-sign -a dist/*whl
twine upload dist/*
