#! /bin/bash

# bdist
# python setup.py check --verbose --metadata --restructuredtext --strict && \
#   python setup.py register sdist upload

python setup.py sdist

twine register dist/*tar.gz
gpg --detach-sign -a dist/*tar.gz
twine upload dist/*tar.gz*
